### ISSUE TITLE
__version__ (Just information)

### ISSUE THREAD

**Issue by PhanterJR** [web2py/pluralize#1]
Just informing. In github the file __init__.py is in version 0.1.2, already in PyPi is in version 0.1.3 that I believe to be the last one. Comparing the two versions has a small change:
## line 108
```
                 self.missing.add(text)
             elif isinstance(translations, dict) and translations:
                 k = max(int(i) for i in translations.keys() if int(i) <= n)
-                text = translations[str(k)].format(**kwargs)
+                text = translations[k].format(**kwargs)
         return text.format(**kwargs)

**Comment by mdipierro** [comment]
text = translations[str(k)].format(**kwargs) is correct because translations are loaded from json, keys are strings.
